version: '3'
services:
  # Backend Specifications
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - database

  # Frontend Specifications
  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050

  # Database Specifications
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

# Creating a custom bridge network
networks:
  mern_network:
    driver: bridge

# Creating volumes for data persistancy or backup
volumes:
  mongo-data:
    driver: local 